/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './pages/**/*.html',
    './js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 - OpenIssue Theme
        'on-surface': '#f4f6fe',
        'secondary-fixed-dim': '#c8bbff',
        'secondary-container': '#49339d',
        'surface': '#0a0e13',
        'background': '#0a0e13',
        'surface-container-lowest': '#000000',
        'on-tertiary-container': '#63054a',
        'on-tertiary-fixed-variant': '#6e1354',
        'on-secondary-container': '#d4c9ff',
        'inverse-surface': '#f8f9ff',
        'primary-container': '#9396ff',
        'surface-container': '#151a20',
        'primary-fixed-dim': '#8387ff',
        'error-container': '#a70138',
        'surface-variant': '#21262e',
        'secondary-dim': '#a28efc',
        'on-tertiary-fixed': '#3b002b',
        'primary-fixed': '#9396ff',
        'outline-variant': '#44484e',
        'on-secondary-fixed-variant': '#533ea7',
        'error': '#ff6e84',
        'tertiary': '#ffa5d9',
        'secondary': '#a28efc',
        'primary-dim': '#6063ee',
        'tertiary-dim': '#ef81c4',
        'on-tertiary': '#701455',
        'outline': '#72767c',
        'primary': '#a3a6ff',
        'surface-tint': '#a3a6ff',
        'on-error': '#490013',
        'on-primary-fixed-variant': '#0e009d',
        'error-dim': '#d73357',
        'tertiary-fixed-dim': '#ef81c4',
        'tertiary-fixed': '#ff8ed2',
        'inverse-on-surface': '#51555b',
        'surface-dim': '#0a0e13',
        'on-primary-container': '#0a0081',
        'on-primary': '#0f00a4',
        'surface-bright': '#262d35',
        'on-primary-fixed': '#000000',
        'tertiary-container': '#ff8ed2',
        'on-surface-variant': '#a8abb2',
        'inverse-primary': '#494bd7',
        'on-background': '#f4f6fe',
        'surface-container-high': '#1b2027',
        'secondary-fixed': '#d6cbff',
        'on-error-container': '#ffb2b9',
        'on-secondary-fixed': '#361c89',
        'surface-container-low': '#0f1419',
        'surface-container-highest': '#21262e',
        'on-secondary': '#21006d',
      },
      borderRadius: {
        DEFAULT: '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'monospace'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
      },
      backdropBlur: {
        xs: '2px',
        sm: '4px',
        DEFAULT: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
      boxShadow: {
        'glass': '0 8px 32px 0 rgba(0, 0, 0, 0.37)',
        'glass-hover': '0 16px 48px 0 rgba(163, 166, 255, 0.2)',
        'glow-primary': '0 0 20px rgba(163, 166, 255, 0.3)',
        'glow-primary-lg': '0 0 30px rgba(163, 166, 255, 0.5)',
        'glow-secondary': '0 0 20px rgba(162, 142, 252, 0.3)',
        'glow-error': '0 0 20px rgba(255, 110, 132, 0.3)',
      },
      animation: {
        'shimmer': 'shimmer 2s infinite linear',
        'fade-in': 'fadeIn 0.6s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'glass-gradient': 'linear-gradient(135deg, rgba(33, 38, 46, 0.4) 0%, rgba(15, 20, 25, 0.6) 100%)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
    // Custom plugin for glassmorphism utilities
    function({ addUtilities }) {
      const newUtilities = {
        '.glass-blur-sm': {
          backdropFilter: 'blur(12px)',
          WebkitBackdropFilter: 'blur(12px)',
        },
        '.glass-blur': {
          backdropFilter: 'blur(20px)',
          WebkitBackdropFilter: 'blur(20px)',
        },
        '.glass-blur-lg': {
          backdropFilter: 'blur(24px)',
          WebkitBackdropFilter: 'blur(24px)',
        },
        '.text-gradient-primary': {
          background: 'linear-gradient(135deg, #a3a6ff 0%, #6063ee 100%)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          backgroundClip: 'text',
        },
        '.text-gradient-secondary': {
          background: 'linear-gradient(135deg, #a28efc 0%, #49339d 100%)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          backgroundClip: 'text',
        },
      }
      addUtilities(newUtilities, ['responsive', 'hover'])
    },
  ],
}
